name: CD SkillLink

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/SkillLink
            git pull origin main
            echo "VITE_API_URL=http://72.62.191.73/api" > frontend/.env.production
            cd frontend
            rm -rf node_modules
            npm install
            npm run build
            cd ..
            docker-compose restart backend